NAME PROG2
STACK SEGMENT STACK
	STA DB 50 DUP(?)
	TOP EQU LENGTH STA
STACK ENDS

DATA SEGMENT
	BUF DB 100 DUP('A')
	BLEN EQU LENGTH BUF
	BEF DB 'Original data is ','$'
	AFT DB 'Changed data is ','$'
DATA ENDS

CODE SEGMENT
	ASSUME CS:CODE,DS:DATA,ES:DATA,SS:STACK
START:
	MOV AX,DATA
	MOV DS,AX
	MOV ES,AX
	MOV AX,STACK
	MOV SS,AX
	MOV SP,TOP;init basic segment
	LEA DX,BEF
	MOV AH,09H
	INT 21H;show 'Original data is'
	MOV CX,BLEN
	LEA SI,BUF
	MOV AH,02H;output an 'A' at a time
BEFSHOW:
	MOV DL,[SI]
	INT 21H
	INC SI
	LOOP BEFSHOW;output all the 'A's
	MOV DL,0AH
	INT 21H;put out a '\n'
	LEA DX,AFT
	MOV AH,09H
	INT 21H;show 'Changed data is '
	MOV CX,BLEN
	LEA SI,BUF
	MOV AH,02H
CHANGE:
	MOV BYTE PTR [SI],'B'
	INC SI
	LOOP CHANGE
	LEA SI,BUF
	MOV CX,BLEN
	MOV AH,02H
AFTSHOW:
	MOV DL,[SI]
	INT 21H
	INC SI
	LOOP AFTSHOW
EXIT:
	MOV AX,4C00H
	INT 21H
CODE ENDS

END START
